# Generated by Django 5.1.5 on 2025-01-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(max_length=200)),
                ('predict_class', models.TextField(max_length=50)),
                ('predict_presntage', models.FloatField(max_length=50)),
            ],
        ),
    ]
